### ISSUE TITLE
IOS 切后台后客户端无法接到推送的问题

### ISSUE THREAD

**Issue by myLog1993** [highras/rtm-client-sdk-unity#1]
请问，IOS切换后台断开连接后，再次切回来客户端为啥无法接到推送呢，文档也没看到相应的内容啊

**Comment by jianjunzhao-github** [comment]
你好，您说的推送是是指RTM本身的消息推送还是离线系统通知？IOS切回前台后会重新建立连接，之后是可以正常收到推送的。您可以通过云上曲率官网的联系方式直接联系我们，我们会针对您的问题提供技术支持。
